### ISSUE TITLE
Compile problems

### ISSUE THREAD

**Issue by thecrazy** [stargieg/bacnet-stack#1]
Hi, I have been looking for a readrange tool and you seem to provide one with your fork of the bacnet protocol stack.

So I have been trying to compile with "make clean demos" but there's errors. Here are the errors in the order I have encountered them and what I have done to try to fix the issues.

Problem #1
Wrong paths in ./demo/Makefile

Solution:  The following paths started with ../../ changed them to ../ as bellow

```
BACNET_PORT_DIR = ../ports/${BACNET_PORT}
BACNET_INCLUDE = ../include
BACNET_OBJECT = ../demo/object
BACNET_HANDLER = ../demo/handler
```

---

Problem #2
Wrong BACNET_LIB_DIR path in ./demo/Makefile

Solution
Not sure if this is ok but since I couldnt find any libbacnet.a in your sources I changed the line to point to the lib folder from bacnet-stack-0.8.2

---

Problem #3
../demo/handler/s_ptransfer.c:50:9: warning: no previous prototype for ‘Send_Private_Transfer_Request’ [-Wmissing-prototypes]
main.c:35:20: fatal error: bacdef.h: No such file or directory

Solution
Not a clue what to do about this one, there are too many path errors in too many files and too many versions of bacdef.h....

---

Problem #4
../src/ucix.c:25:24: fatal error: uci_config.h: No such file or directory

Solution
Not a clue here either, what is an UCI? were can I get this file?

And there are a bunch of other path errors if we do a "make clean all"
Also, there is probably a bunch of other errors up ahead cause I havent been able to get past problem #3 yet.

Could you please help?

**Comment by arvindpdmn** [comment]
I took a clone of the repo. I am getting this:
`~/workspace/bacnet-stack$ make clean all
make -s -C lib clean
make -s -C demo clean
make -s -C demo/router clean
make -s -C lib all
../src/ucix.c:25:24: fatal error: uci_config.h: No such file or directory
 #include <uci_config.h>
                        ^
compilation terminated.
make[1]: *** [../src/ucix.o] Error 1
make: *** [library] Error 2
`
Since you said something about OpenWrt, I cloned that as well but did not find this header file. I then cloned UCI and I found uci_config.h.in but not  uci_config.h. But I have no idea how to bring these things together. Please help.

**Comment by arvindpdmn** [comment]
I tried compiling UCI without OpenWRT (http://wiki.openwrt.org/doc/techref/uci#usage_outside_of_openwrt) but looks like there is still a dependency with OpenWRT's libubox:

	~/workspace/uci$ make install
	Scanning dependencies of target uci
	[ 12%] Building C object CMakeFiles/uci.dir/libuci.c.o
	[ 25%] Building C object CMakeFiles/uci.dir/file.c.o
	[ 37%] Building C object CMakeFiles/uci.dir/util.c.o
	[ 50%] Building C object CMakeFiles/uci.dir/delta.c.o
	[ 62%] Building C object CMakeFiles/uci.dir/parse.c.o
	[ 75%] Building C object CMakeFiles/uci.dir/blob.c.o
	/home/xxx/workspace/uci/blob.c:18:29: fatal error: libubox/blobmsg.h: No such file or directory
	 #include <libubox/blobmsg.h>
	                             ^
	compilation terminated.
	make[2]: *** [CMakeFiles/uci.dir/blob.c.o] Error 1
	make[1]: *** [CMakeFiles/uci.dir/all] Error 2
	make: *** [all] Error 2

**Comment by stargieg** [comment]
hi arvindpdmn
Please read https://github.com/stargieg/bacnet-stack/wiki/Install
This port of bacnet-stack is for openwrt. If you have an openwrt build environment then you can use
my feed: https://github.com/stargieg/packages-automation

**Comment by arvindpdmn** [comment]
Wow! That worked! My mistake, I should have checked the wiki page as well. Thanks a lot.

Do I have to do a port for MSP430 or is that available in this implementation?
